Fix failed request cookies
BrowseAI-Official/puppeteer-page-proxy pull request #1
Opened 2021-02-19 01:16 UTC by MoradiDavijani

Related issue: https://github.com/Cuadrix/puppeteer-page-proxy/issues/36

2021-02-19 01:54 UTC, ardalann requested changes
Almost there!

P.S. I love the PR review experience on Github lol

2021-02-19 01:54 UTC, ardalann commented on src/lib/cookies.js
> +        this.url = request.isNavigationRequest() ? request.url() : request.frame()?.url() || request.url();
I don't think this works. Example: https://codepen.io/ardalann/pen/RwogYdj?editors=1111

2021-02-19 02:01 UTC, ardalann commented on src/lib/cookies.js
> +        this.url = request.isNavigationRequest() ? request.url() : request.frame()?.url() || request.url();
UPDATE: My example was wrong! this works: https://codepen.io/ardalann/pen/RwogYdj?editors=1111

2021-02-19 02:01 UTC, merged

2022-02-08 13:44 UTC, wynnfarm commented
Hello, I am seeing 4 issues related to this bug.  Is this ready to be merged back into the main project and a new version published?